name: Example Workflow Using the SecureStack Log4j Scanning GitHub Action
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for running secrets analysis within workflow
        id: checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Experiment
        run: |
          pwd
          ls -al
      - name: log4j Scanning Step
        id: log4j
        uses: SecureStackCo/actions-log4j@v0.1.3
        with:
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          severity: medium
